version: '3.8'

networks:
  kafka-bridge:
    driver: bridge

services:
  tt-zookeeper:
    hostname: lonezk
    image: confluentinc/cp-zookeeper:latest
    container_name: tt-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - ./volumes/zookeeper:/var/lib/zookeeper/data
      - ./volumes/zookeeper:/var/lib/zookeeper/log
    networks:
      - kafka-bridge
  tt-kafka:
    hostname: lonekafka
    image: confluentinc/cp-kafka:latest
    container_name: tt-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: tt-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://tt-kafka:19092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "booking-request:1:1,booking-response:1:1"
    volumes:
      - ./volumes/kafka:/var/lib/kafka/data
    depends_on:
      - tt-zookeeper
    networks:
      - kafka-bridge